# Generated by Django 4.2.5 on 2023-09-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0010_commentreplies_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplies',
            name='self_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blogapp.commentreplies'),
        ),
    ]
